### ISSUE TITLE
建议将其改为类库版本2.0

### ISSUE THREAD

**Issue by MuJint** [AmmRage/WordCloudSharp#1]
还有个问题，因为是引用的System.Drawing.Common，如果在linux环境下将会存在中文异常。
据查，好像是因为`System.Drawing.Common.dll 中的GdipDrawString 居然少了CharSet 标记`
引用自[出处](https://www.lmlphp.com/user/8701/article/item/385681/)

**Comment by l972860692** [comment]
WordCloudSharp FastImage  Byte[] Can't be  recycled By GC。
![image](https://user-images.githubusercontent.com/6511721/161378092-da29452e-5e78-4d8c-a6ba-1f66bc8c88e5.png)

**Comment by MuJint** [comment]
> WordCloudSharp FastImage Byte[] Can't be recycled By GC。 ![image](https://user-images.githubusercontent.com/6511721/161378092-da29452e-5e78-4d8c-a6ba-1f66bc8c88e5.png)

I changed the code a little bit. Not yet merged into the main thread, multiple threads running at the same time eventually memory and CPU are fine, GC is fine. Address: https://github.com/MuJint/WordCloudCsharp

**Comment by MuJint** [comment]
> 

Please leave a message if you have any questions.

**Comment by AmmRage** [comment]
sdk changed to suggested already by merging https://github.com/AmmRage/WordCloudSharp/pull/3
thx
sdk版本已经修改
谢谢
