### ISSUE TITLE
[功能请求] .net core支持

### ISSUE THREAD

**Issue by GardenHamster** [AmmRage/WordCloudSharp#5]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
大佬的项目真是泰裤辣，但是System.Drawing库对一些Linux版本表现不太友好，请问佬可以做一个跨平台改的版本吗，图片处理可以用SkiaSharp

**Describe alternatives you've considered**
SkiaSharp

**Additional context**

**Comment by AmmRage** [comment]
哪些版本？

**Comment by GardenHamster** [comment]
暂时不需要了,谢谢佬
